### ISSUE TITLE
Unnecessary native plugin for native build while at SpringBoot version 3

### ISSUE THREAD

**Issue by patpatpat123** [jumtp/SpringBoot3-log-build-error#1]
Very cool project!

Small observation on your pom.xml, especially the native plugin.

https://github.com/jumtp/SpringBoot3-log-build-error/blob/master/pom.xml#L36

SpringBoot 3 comes with the -Pnative profile, therefore, the extra plugin is really necessary? 

Thank you

**Comment by jumtp** [comment]
necessary. but This project is just an example. In order to let the SpringBoot official team fix some errors. But it is not a Spring problem ,ts[https://github.com/spring-projects/spring-boot/issues/33840](https://github.com/spring-projects/spring-boot/issues/33840)
